production:
  address:        localhost
  port:           25
  domain:         localhost
  user_name:      
  password:       
  authentication: 

test:
  address:        localhost
  port:           25
  domain:         localhost
  user_name:      
  password:       
  authentication: 

development:
  address:        localhost
  port:           25
  domain:         localhost
  user_name:      
  password:       
  authentication: 
